/**
 * The 24 solar terms (二十四节气), 1900..2100, as exact UTC instants.
 *
 * Data: `data/solar-terms.json` — per year, 24 integers = seconds since Jan 1 00:00 UTC of that year.
 * Generated by `tools/gen_solar_terms.py` from sxtwl and cross-checked against lunar_python
 * (max disagreement 55 s across all 4,824 instants; see fixtures/solar-terms-1900-2100.json).
 */
import table from "./data/solar-terms.json";
import { MIN_YEAR, MAX_YEAR } from "./lunar";
import { type DateInput, toCivil } from "./input";
import { civilDayBounds } from "./tz";

const TABLE = table as unknown as Record<string, number[]>;

export interface SolarTermName { zh: string; en: string; longitude: number }

/** Index 0 = 小寒 (first term of the civil year) … 23 = 冬至. */
export const SOLAR_TERM_NAMES: readonly SolarTermName[] = [
  { zh: "小寒", en: "Minor Cold", longitude: 285 },
  { zh: "大寒", en: "Major Cold", longitude: 300 },
  { zh: "立春", en: "Beginning of Spring", longitude: 315 },
  { zh: "雨水", en: "Rain Water", longitude: 330 },
  { zh: "惊蛰", en: "Awakening of Insects", longitude: 345 },
  { zh: "春分", en: "Spring Equinox", longitude: 0 },
  { zh: "清明", en: "Pure Brightness", longitude: 15 },
  { zh: "谷雨", en: "Grain Rain", longitude: 30 },
  { zh: "立夏", en: "Beginning of Summer", longitude: 45 },
  { zh: "小满", en: "Grain Buds", longitude: 60 },
  { zh: "芒种", en: "Grain in Ear", longitude: 75 },
  { zh: "夏至", en: "Summer Solstice", longitude: 90 },
  { zh: "小暑", en: "Minor Heat", longitude: 105 },
  { zh: "大暑", en: "Major Heat", longitude: 120 },
  { zh: "立秋", en: "Beginning of Autumn", longitude: 135 },
  { zh: "处暑", en: "End of Heat", longitude: 150 },
  { zh: "白露", en: "White Dew", longitude: 165 },
  { zh: "秋分", en: "Autumn Equinox", longitude: 180 },
  { zh: "寒露", en: "Cold Dew", longitude: 195 },
  { zh: "霜降", en: "Frost's Descent", longitude: 210 },
  { zh: "立冬", en: "Beginning of Winter", longitude: 225 },
  { zh: "小雪", en: "Minor Snow", longitude: 240 },
  { zh: "大雪", en: "Major Snow", longitude: 255 },
  { zh: "冬至", en: "Winter Solstice", longitude: 270 },
];

export interface SolarTerm {
  year: number;        // civil year the instant falls in
  index: number;       // 0..23, see SOLAR_TERM_NAMES
  name: SolarTermName;
  at: Date;            // exact UTC instant
}

function yearStartMs(year: number): number { return Date.UTC(year, 0, 1); }

function checkYear(year: number): void {
  if (year < MIN_YEAR || year > MAX_YEAR) throw new RangeError(`Year ${year} out of range ${MIN_YEAR}..${MAX_YEAR}`);
}

/** All 24 terms of a civil year, in order. */
export function solarTerms(year: number): SolarTerm[] {
  checkYear(year);
  const base = yearStartMs(year);
  return TABLE[String(year)].map((sec, index) => ({
    year, index, name: SOLAR_TERM_NAMES[index], at: new Date(base + sec * 1000),
  }));
}

/** The term in effect at `instant` (last term whose instant <= given), and the next one. */
export function solarTermAt(instant: Date): { current: SolarTerm; next: SolarTerm } {
  const year = instant.getUTCFullYear();
  checkYear(year);
  const t = instant.getTime();
  const list = [
    ...(year > MIN_YEAR ? solarTerms(year - 1).slice(-1) : []),
    ...solarTerms(year),
    ...(year < MAX_YEAR ? solarTerms(year + 1).slice(0, 1) : []),
  ];
  let i = -1;
  for (let k = 0; k < list.length; k++) if (list[k].at.getTime() <= t) i = k;
  if (i < 0 || i + 1 >= list.length) throw new RangeError("Instant outside supported range");
  return { current: list[i], next: list[i + 1] };
}

/**
 * The term (if any) whose instant falls on the civil day (y, m, d) as observed in `tz`:
 * an IANA zone id ("Asia/Tokyo", DST-aware) or a fixed UTC offset in minutes. Default +08:00 (Beijing),
 * which is what Chinese almanacs use.
 */
export function solarTermOnDay(input: DateInput, tz: string | number = 480): SolarTerm | null {
  const civil = toCivil(input);
  const [dayStart, dayEnd] = civilDayBounds(civil, tz);
  const { year: y, month: m } = civil;
  const candidates = [
    ...(m === 1 && y > MIN_YEAR ? solarTerms(y - 1).slice(-1) : []),
    ...solarTerms(y),
    ...(m === 12 && y < MAX_YEAR ? solarTerms(y + 1).slice(0, 1) : []),
  ];
  return candidates.find(s => s.at.getTime() >= dayStart && s.at.getTime() < dayEnd) ?? null;
}
