"""Canonical festival crosswalk + zh-Hans names for baseline regions. Shared by the generators."""
import re

# (regex on english name, canonical festival id, zh-Hans name)
FESTIVALS = [
    (r"^(?!.*(chinese|lunar|korean|vietnamese|tết)).*(new year'?s? day|first day of january|^new year$|january 1)", "new-year", "元旦"),
    (r"new year'?s? eve|除夕|giao thừa|day (preceding|before) .*new year", "lunar-new-year-eve", "除夕"),
    (r"chinese new year|lunar new year|korean new year|seollal|tết nguyên đán|spring festival", "lunar-new-year", "春节"),
    (r"ching ming|qingming|tomb[- ]sweeping", "qingming", "清明节"),
    (r"tuen ng|dragon boat|duanwu", "dragon-boat", "端午节"),
    (r"mid[- ]autumn|chuseok|day following the chinese mid", "mid-autumn", "中秋节"),
    (r"chung yeung|double ninth", "double-ninth", "重阳节"),
    (r"labou?r day|may day|workers'? day|international workers", "labour-day", "劳动节"),
    (r"national day|independence day|bastille|german unity|tag der deutschen einheit|foundation day|gaecheonjeol|quốc khánh|hksar establishment|liberation day", "national-day", "国庆日"),
    (r"christmas day|christmas", "christmas", "圣诞节"),
    (r"boxing day|second day of christmas|st\.? stephen", "boxing-day", "节礼日"),
    (r"good friday", "good-friday", "耶稣受难日"),
    (r"easter monday", "easter-monday", "复活节星期一"),
    (r"easter sunday|easter", "easter", "复活节"),
    (r"ascension", "ascension", "耶稣升天节"),
    (r"whit monday|pentecost monday", "whit-monday", "圣灵降临节星期一"),
    (r"whit sunday|pentecost", "whit-sunday", "圣灵降临节"),
    (r"all saints", "all-saints", "诸圣节"),
    (r"assumption", "assumption", "圣母升天节"),
    (r"armistice|remembrance|veterans", "armistice", "停战纪念日"),
    (r"victory in europe|victoire 1945", "ve-day", "欧战胜利日"),
    (r"buddha'?s? birthday|vesak|wesak", "vesak", "佛诞"),
    (r"hari raya puasa|eid al-fitr|eid ul-fitr", "eid-al-fitr", "开斋节"),
    (r"hari raya haji|eid al-adha", "eid-al-adha", "宰牲节"),
    (r"deepavali|diwali", "deepavali", "屠妖节"),
    (r"thanksgiving", "thanksgiving", "感恩节"),
    (r"memorial day", "memorial-day", "阵亡将士纪念日"),
    (r"martin luther king", "mlk-day", "马丁·路德·金纪念日"),
    (r"washington'?s? birthday|presidents'? day", "presidents-day", "总统日"),
    (r"juneteenth", "juneteenth", "六月节"),
    (r"columbus|indigenous peoples", "columbus-day", "哥伦布日"),
    (r"coming of age", "coming-of-age", "成人节"),
    (r"emperor'?s? birthday", "emperors-birthday", "天皇诞生日"),
    (r"vernal equinox", "vernal-equinox", "春分"),
    (r"autumnal equinox", "autumnal-equinox", "秋分"),
    (r"showa day", "showa-day", "昭和日"),
    (r"constitution", "constitution-day", "宪法纪念日"),
    (r"greenery day", "greenery-day", "绿之日"),
    (r"children'?s? day", "childrens-day", "儿童节"),
    (r"marine day|sea day", "marine-day", "海之日"),
    (r"mountain day", "mountain-day", "山之日"),
    (r"respect for the aged", "respect-aged-day", "敬老日"),
    (r"sports day|health and sports", "sports-day", "体育日"),
    (r"culture day", "culture-day", "文化日"),
    (r"labor thanksgiving", "labor-thanksgiving", "勤劳感谢日"),
    (r"hangul", "hangeul-day", "韩文日"),
    (r"buddha", "vesak", "佛诞"),
    (r"hung kings", "hung-kings", "雄王纪念日"),
    (r"reunification", "reunification-day", "统一日"),
    (r"peace memorial|228", "peace-memorial", "和平纪念日"),
    (r"early may bank|spring bank|summer bank|august bank|bank holiday", "bank-holiday", "银行假日"),
    (r"^national holiday$", "national-holiday", "国民休日"),
    (r"independence movement", "independence-movement", "三一节"),
    (r"armed forces day", "armed-forces-day", "国军日"),
    (r"election day|polling day", "election-day", "选举日"),
    (r"temporary public holiday", "temporary-holiday", "临时公休日"),
    (r"victory day", "ve-day", "胜利日"),
    (r"epiphany|three kings", "epiphany", "主显节"),
    (r"corpus christi", "corpus-christi", "基督圣体节"),
    (r"reformation", "reformation-day", "宗教改革日"),
    (r"repentance", "repentance-day", "忏悔祈祷日"),
    (r"women'?s day", "womens-day", "妇女节"),
    (r"saint patrick|st\.? patrick", "st-patricks-day", "圣帕特里克节"),
    (r"saint andrew|st\.? andrew", "st-andrews-day", "圣安德鲁日"),
    (r"battle of the boyne", "boyne", "博因河战役纪念日"),
    (r"new year holiday", "new-year-holiday", "新年假期次日"),
    (r"all souls", "all-souls", "万灵节"),
    (r"holy thursday|maundy", "maundy-thursday", "濯足节"),
    (r"emancipation", "emancipation-day", "解放日"),
    (r"statehood|state holiday|admission day", "statehood-day", "建州日"),
    (r"lincoln", "lincolns-birthday", "林肯诞辰"),
    (r"president'?s day|washington", "presidents-day", "总统日"),
    (r"patriots'? day", "patriots-day", "爱国者日"),
    (r"pioneer day", "pioneer-day", "拓荒者日"),
    (r"mardi gras", "mardi-gras", "狂欢节"),
    (r"inauguration", "inauguration-day", "就职日"),
    (r"arbor day", "arbor-day", "植树节"),
    (r"citizenship", "citizenship-day", "公民日"),
    (r"town meeting", "town-meeting-day", "镇民大会日"),
    (r"native american|american indian|indigenous", "native-american-day", "原住民日"),
    (r"anniversary", "anniversary", "周年纪念日"),
    (r"substitute|observed|振替|in lieu|following|alternative holiday|day off for", "substitute", "补假"),
]
COMPILED = [(re.compile(p, re.I), fid, zh) for p, fid, zh in FESTIVALS]

def classify(en_name: str):
    """Return (festival_id, zh_hans) or (None, None)."""
    for rx, fid, zh in COMPILED:
        if rx.search(en_name): return fid, zh
    return None, None

BCP47 = {"zh_CN": "zh-Hans", "zh_TW": "zh-Hant-TW", "zh_HK": "zh-Hant-HK", "zh_MO": "zh-Hant-MO",
         "en_US": "en", "en_GB": "en", "en_SG": "en", "en_HK": "en", "en_MO": "en", "ja": "ja", "ko": "ko",
         "vi": "vi", "de": "de", "fr": "fr", "pt_MO": "pt", "th": "th"}
